services:
  - type: web
    runtime: docker
    name: tradejournalVM
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /login
    envVars:
      - key: PORT
        value: "10000"
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: tradejournal-dbVM
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: tradejournal-dbVM
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: tradejournal-dbVM
          property: password
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.postgresql.Driver
      - key: SPRING_JPA_DATABASE_PLATFORM
        value: org.hibernate.dialect.PostgreSQLDialect
